### ISSUE TITLE
why two bibliographies?

### ISSUE THREAD

**Issue by fabianp** [iclr-blogposts/2024#12]
I currently see in the repo _bibliography/papers.bib and assets/bibliography/2024-05-07-distill-example.bib. 

What is the first one used for? do we need both?

**Comment by busycalibrating** [comment]
I think the `_bibliography/papers.bib` is for displaying 'your published work' if you use this template as a CV. We could potentially use to to post the published papers (i.e. from the contents of [this search](https://github.com/search?q=repo%3Aalshedivat%2Fal-folio%20papers.bib&type=code)). We can empty out the citation for cleanliness, but maybe keep the file? What do you think?

**Comment by Velythyl** [comment]
I think we should just delete the file. But tbh a lot of the files in the repo are useless: last year, we just removed all of the links that used to lead to them from the main page

**Comment by fabianp** [comment]
done in ddfe7aeffaab5cbe7c20634999963bc99db57afb
