### ISSUE TITLE
Figures not updated on the deployed blogpost

### ISSUE THREAD

**Issue by MatDag** [iclr-blogposts/2024#129]
Hi,

When pushing a modified figure in the blogpost repo, the modification is not taken into account in the deployed blogpost under the url `https://d2jud02ci9yv69.cloudfront.net/2024-05-07-[SUBMISSION NAME]`. The figure `https://d2jud02ci9yv69.cloudfront.net/2024-05-07-[SUBMISSION NAME]/assets/img/2024-05-07-[SUBMISSION NAME]/my_figure.png` is still the first version of the figure which differs from the one in the repo.

**Comment by fabianp** [comment]
Hi Mathieu and thanks for the report. There was some caching in the server that I've now disabled. Could you let me know if that solves the problem?

and if not, could you send me the link to both the image on github and the one in d2jud02ci9yv69.cloudfront.net ? Thanks

**Comment by MatDag** [comment]
Thank you for your prompt reply! 
The problem remains. This affects two images:
* Image 1: [d2jud02ci9yv69.cloudfront.net](https://d2jud02ci9yv69.cloudfront.net/2024-05-07-bench-hvp-81/assets/img/2024-05-07-bench-hvp/computational_graph.png) / [GitHub](https://github.com/MatDag/hessian_vector_products/blob/blogpost/assets/img/2024-05-07-bench-hvp/computational_graph.png)
* Image 2: [d2jud02ci9yv69.cloudfront.net](https://d2jud02ci9yv69.cloudfront.net/2024-05-07-bench-hvp-81/assets/img/2024-05-07-bench-hvp/bench_hvp_memory_jax.png) / [GitHub](https://github.com/MatDag/hessian_vector_products/blob/blogpost/assets/img/2024-05-07-bench-hvp/bench_hvp_memory_jax.png)

**Comment by fabianp** [comment]
To me they look the same both (although I haven't looked too much in detail, there could be some subtle changes I'm missing). Could it by any chance be your browser caching the cloudfront image?

![Screenshot from 2023-12-14 07-45-30](https://github.com/iclr-blogposts/2024/assets/277639/7c1babd5-b959-4c2b-ae8a-51318a6960d4)

![Screenshot from 2023-12-14 07-44-33](https://github.com/iclr-blogposts/2024/assets/277639/ea0561b5-7b5d-42a0-a8a8-d63b578c2675)

**Comment by MatDag** [comment]
Indeed, it was the cache of my browser! Thanks a lot for your help!

**Comment by fabianp** [comment]
no problem
