### ISSUE TITLE
Can't add PR label; and confusion about submission URL

### ISSUE THREAD

**Issue by dasayan05** [iclr-blogposts/2024#59]
1. Hi @fabianp, how do I add `submission` label to PR ?

2. The URL that I get after the PR build is `https://xxxxxxxx.cloudfront.net/2024-05-07-submission-name/`. But openreview is expecting (erroring otherwise) something like `https://iclr-blogposts.github.io/2024/blog/[YOUR_SUBMISSION]/`. Where do I get the submittable URL ?

**Comment by fabianp** [comment]
hi @dasayan05 , and thanks for the report.

1. You shouldn't need to add the "submission" label. Is there anything in the doc or elsewhere that made you think otherwise?
2. @SchwinnL : this seems like an error. I believe you've been working on this front. Could you take a look into it?

**Comment by dasayan05** [comment]
1. Point 4 of the "Quickstart" section [here](https://iclr-blogposts.github.io/2024/submitting/) says so.
2. Thanks.

**Comment by fabianp** [comment]
1. Excellent, I just removed it. It was outdated information

**Comment by Velythyl** [comment]
Also, I encourage you to sync your repository with the main branch before doing your PR. This is just in case the github Action on your end (that does expect the PR label) overrides ours (that does not expect the PR label).

**Comment by SchwinnL** [comment]
Hi  @dasayan05 thanks for the report! 

You should be able to submit your post with the cloudfront URL now 

Best,
Leo
